FROM python:3.11-slim

WORKDIR /app

# Copie uniquement les fichiers nécessaires au service Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY chatbot_service.py .

EXPOSE 5005

CMD ["python", "chatbot_service.py"]
